#!/usr/bin/env bash
# One-time setup: fetch Azure DEV secrets and generate .env.cloud
# Re-run after DEV environment stop/start cycle (Redis key changes).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.cloud"

RG="rg-imggen-dev"
PG_NAME="psql-imggen-dev2"
PG_DB="imggen"
PG_USER="imggenadmin"
REDIS_NAME="redis-imggen-dev"
STORAGE_ACCOUNT="stimggendev"
STORAGE_CONTAINER="images"

echo "=== Setting up .env.cloud for Azure DEV ==="
echo ""

# Check Azure CLI is logged in
if ! az account show &>/dev/null; then
    echo "ERROR: Not logged in to Azure CLI. Run: az login"
    exit 1
fi

# 1. Fetch Redis key
echo "--- Fetching Redis access key ---"
REDIS_KEY=$(az redis list-keys --resource-group "$RG" --name "$REDIS_NAME" --query "primaryKey" -o tsv 2>/dev/null || echo "")
if [ -z "$REDIS_KEY" ]; then
    echo "  WARNING: Could not fetch Redis key. Is the DEV environment running?"
    echo "  Run ./scripts/dev-env-start.sh first, then re-run this script."
    REDIS_KEY="REDIS_KEY_NOT_FOUND"
else
    echo "  OK"
fi

# 2. Fetch Storage connection string
echo "--- Fetching Storage connection string ---"
STORAGE_CONN=$(az storage account show-connection-string --resource-group "$RG" --name "$STORAGE_ACCOUNT" --query "connectionString" -o tsv 2>/dev/null || echo "")
if [ -z "$STORAGE_CONN" ]; then
    echo "  WARNING: Could not fetch Storage connection string."
    STORAGE_CONN="STORAGE_CONNECTION_STRING_NOT_FOUND"
else
    echo "  OK"
fi

# 3. Prompt for DB password
echo ""
echo "--- Database password ---"
echo "  PostgreSQL user: $PG_USER@$PG_NAME"
read -rsp "  Enter DB password: " DB_PASSWORD
echo ""
if [ -z "$DB_PASSWORD" ]; then
    echo "  WARNING: Empty password. You'll need to edit .env.cloud manually."
    DB_PASSWORD="PASSWORD"
fi

# 4. Check for JWT secret (optional)
JWT_SECRET=""
echo ""
echo "--- JWT secret (optional) ---"
echo "  Leave blank to use the backend default, or paste the DEV cloud JWT secret"
echo "  to share sessions between local and cloud."
read -rsp "  JWT secret (Enter to skip): " JWT_SECRET
echo ""

# 5. API keys — managed per-user via Settings UI, no env var fallback

# 6. Write .env.cloud
echo ""
echo "--- Writing $ENV_FILE ---"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-cloud-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run ./scripts/setup-cloud-env.sh if Redis key or credentials change.

# PostgreSQL (Azure Flexible Server)
DATABASE_URL=postgresql://${PG_USER}:${DB_PASSWORD}@${PG_NAME}.postgres.database.azure.com:5432/${PG_DB}?sslmode=require

# Redis (Azure Cache for Redis — TLS)
REDIS_URL=rediss://:${REDIS_KEY}@${REDIS_NAME}.redis.cache.windows.net:6380/0
CELERY_BROKER_URL=rediss://:${REDIS_KEY}@${REDIS_NAME}.redis.cache.windows.net:6380/1
CELERY_RESULT_BACKEND=rediss://:${REDIS_KEY}@${REDIS_NAME}.redis.cache.windows.net:6380/2

# Azure Blob Storage
STORAGE_BACKEND=azure
AZURE_STORAGE_CONNECTION_STRING="${STORAGE_CONN}"
AZURE_STORAGE_CONTAINER=${STORAGE_CONTAINER}

# Environment
ENVIRONMENT=dev
NEXT_PUBLIC_ENV_LABEL=cloud-native

# JWT
JWT_SECRET_KEY=${JWT_SECRET}

# API keys — managed per-user via Settings UI
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
FAL_API_KEY=
EOF

echo "  Created: $ENV_FILE"
echo ""
echo "=== Done! Next steps: ==="
echo "  1. Run: cura cloud-native    (native hot-reload development)"
echo "  2. Or:  cura cloud-docker   (Docker with cloud resources)"
