"""Add users table and user_id to all main tables.

Revision ID: 017_users
Revises: 016_pair_type
"""
import sqlalchemy as sa
from alembic import op

revision = "017_users"
down_revision = "016_pair_type"
branch_labels = None
depends_on = None

# Pre-computed bcrypt hash of "password"
SEED_HASHED_PASSWORD = "$2b$12$wc4zDqaPwXb25LUfYXR2C.q63on3ppEP35CE0tbACmhc6SFoDUxsC"

# Tables that get a NOT NULL user_id column
TABLES_NOT_NULL = [
    "images",
    "folders",
    "clusters",
    "jobs",
    "lora_models",
    "generated_images",
    "lora_evaluations",
    "prompt_presets",
    "app_settings",
    "api_keys",
]

# Tables that get a nullable user_id column
TABLES_NULLABLE = [
    "pipeline_logs",
]

ALL_TABLES = TABLES_NOT_NULL + TABLES_NULLABLE


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # 1. Create users table
    # ------------------------------------------------------------------ #
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("hashed_password", sa.String(128), nullable=False),
        sa.Column("display_name", sa.String(256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("verification_code", sa.String(64), nullable=True),
        sa.Column("verification_code_expires_at", sa.DateTime(), nullable=True),
        sa.Column("role", sa.String(16), nullable=False, server_default="user"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_id", "users", ["id"])
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # ------------------------------------------------------------------ #
    # 2. Seed admin user
    # ------------------------------------------------------------------ #
    op.execute(
        sa.text(
            "INSERT INTO users (email, hashed_password, display_name, is_active, is_verified, role, created_at, updated_at) "
            "VALUES (:email, :hashed_password, :display_name, true, true, 'admin', NOW(), NOW())"
        ).bindparams(
            email="stuart.leal23@gmail.com",
            hashed_password=SEED_HASHED_PASSWORD,
            display_name="Stuart",
        )
    )

    # ------------------------------------------------------------------ #
    # 3. Add user_id to all tables, backfill, set NOT NULL + FK + index
    # ------------------------------------------------------------------ #
    for table in TABLES_NOT_NULL:
        op.add_column(table, sa.Column("user_id", sa.Integer(), nullable=True))
        op.execute(f"UPDATE {table} SET user_id = (SELECT id FROM users LIMIT 1)")
        op.alter_column(table, "user_id", nullable=False)
        op.create_foreign_key(f"fk_{table}_user_id", table, "users", ["user_id"], ["id"], ondelete="CASCADE")
        op.create_index(f"ix_{table}_user_id", table, ["user_id"])

    for table in TABLES_NULLABLE:
        op.add_column(table, sa.Column("user_id", sa.Integer(), nullable=True))
        op.execute(f"UPDATE {table} SET user_id = (SELECT id FROM users LIMIT 1)")
        # keep nullable
        op.create_foreign_key(f"fk_{table}_user_id", table, "users", ["user_id"], ["id"], ondelete="CASCADE")
        op.create_index(f"ix_{table}_user_id", table, ["user_id"])

    # ------------------------------------------------------------------ #
    # 4. Drop old unique constraints & create composite ones
    # ------------------------------------------------------------------ #

    # images.file_hash — was a unique index created in 001
    op.drop_index("ix_images_file_hash", table_name="images", if_exists=True)
    op.create_unique_constraint("uq_images_user_file_hash", "images", ["user_id", "file_hash"])

    # prompt_presets.name — unique constraint auto-generated by SA column(unique=True) in 006
    op.drop_constraint("prompt_presets_name_key", "prompt_presets", type_="unique")
    op.create_unique_constraint("uq_prompt_presets_user_name", "prompt_presets", ["user_id", "name"])

    # app_settings.key — was a unique index created in 002
    op.drop_index("ix_app_settings_key", table_name="app_settings", if_exists=True)
    op.create_unique_constraint("uq_app_settings_user_key", "app_settings", ["user_id", "key"])

    # api_keys.provider — unique constraint auto-generated by SA column(unique=True) in 012
    op.drop_constraint("api_keys_provider_key", "api_keys", type_="unique")
    op.create_unique_constraint("uq_api_keys_user_provider", "api_keys", ["user_id", "provider"])


def downgrade() -> None:
    # ------------------------------------------------------------------ #
    # 4 (reverse). Drop composite unique constraints, restore old ones
    # ------------------------------------------------------------------ #

    # api_keys
    op.drop_constraint("uq_api_keys_user_provider", "api_keys", type_="unique")
    op.create_unique_constraint("api_keys_provider_key", "api_keys", ["provider"])

    # app_settings
    op.drop_constraint("uq_app_settings_user_key", "app_settings", type_="unique")
    op.create_index("ix_app_settings_key", "app_settings", ["key"], unique=True)

    # prompt_presets
    op.drop_constraint("uq_prompt_presets_user_name", "prompt_presets", type_="unique")
    op.create_unique_constraint("prompt_presets_name_key", "prompt_presets", ["name"])

    # images
    op.drop_constraint("uq_images_user_file_hash", "images", type_="unique")
    op.create_index("ix_images_file_hash", "images", ["file_hash"], unique=True)

    # ------------------------------------------------------------------ #
    # 3 (reverse). Drop FK constraints, indexes, and user_id columns
    # ------------------------------------------------------------------ #
    for table in ALL_TABLES:
        op.drop_constraint(f"fk_{table}_user_id", table, type_="foreignkey")
        op.drop_index(f"ix_{table}_user_id", table_name=table)
        op.drop_column(table, "user_id")

    # ------------------------------------------------------------------ #
    # 1 (reverse). Drop users table
    # ------------------------------------------------------------------ #
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
